# Generated by Django 4.0.5 on 2022-06-05 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dolist', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='toodoo',
            name='place',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='toodoo',
            name='status',
            field=models.CharField(max_length=100),
        ),
    ]
